### ISSUE TITLE
backup zip contains ".pyo" files 

### ISSUE THREAD

**Issue by rrosajp** [jewbmx/script.ezclean#1]
hi jewbmx ,
here is modified wiz.py but i don't know how to push/ pull on GitHub  so i attach the links of  [file ](https://gist.github.com/rrosajp/93b8011a8778d2e78f7b61801478e24d)

**Comment by jewbmx** [comment]
Sorry didnt see this till now lol. Thanks for the help, i'll add your changes in. Been sorting and cleaning everything up but dont think i made it to wiz.py yet.

**Comment by jewbmx** [comment]
Been testing the backup/restore a bit more and it seems pretty solid beside a couple little settings not being saved in my skin lol and it loading back into the stock skin is a little confusing at first.

**Comment by jewbmx** [comment]
Found another issue or glitch, the userdata restore stuff seems to be extracting the zip inside the userdata folder so it ends up like /userdata/userdata/ lol.
